Fix for issue #33
VedalAI/neuro-game-sdk pull request #34
Opened 2024-12-30 23:24 UTC by miles-igd

When a Godot project is exported the resources are renamed. Mainly .remap is added to the end so this simply removes it.

2025-01-03 08:43 UTC, Alexejhero requested changes

2025-01-03 08:43 UTC, Alexejhero commented on Godot/addons/neuro-sdk/websocket/command_handler.gd
> +			file_name = file_name.replace(".remap", "")
☝🤓 actually if you have a file called `something.remap.gd` this will break because it will retarget to `something..gd`

2025-01-03 11:07 UTC, miles-igd commented on Godot/addons/neuro-sdk/websocket/command_handler.gd
> +			file_name = file_name.replace(".remap", "")
Thanks I've changed it to trim_suffix so that only the one .remap is removed if it exists.

2025-01-05 09:29 UTC, Alexejhero approved these changes

2025-01-05 09:29 UTC, merged